### ISSUE TITLE
按照教程运行报错了

### ISSUE THREAD

**Issue by CharlesJames13586** [w-x-x-w/HandwritingGenerator#1]
```shell
(venv)xxxx@MacBook-Pro-3 HandwritingGenerator % python main.py
Traceback (most recent call last):
  File "/Users/xxxx/Desktop/wsp/python/HandwritingGenerator/main.py", line 569, in <module>
    viewer = HandFontWindow()
             ^^^^^^^^^^^^^^^^
  File "/Users/xxxx/Desktop/wsp/python/HandwritingGenerator/main.py", line 133, in __init__
    self.initUI()
  File "/Users/xxxx/Desktop/wsp/python/HandwritingGenerator/main.py", line 155, in initUI
    self.updateView()
  File "/Users/xxxx/Desktop/wsp/python/HandwritingGenerator/main.py", line 354, in updateView
    self.view.addTextItem(text=text_tmp, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/Desktop/wsp/python/HandwritingGenerator/main.py", line 508, in addTextItem
    font_family = QFontDatabase.applicationFontFamilies(font_id)[0]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by CharlesJames13586** [comment]
作者你好，按照教程运行的`python main.py`时报错了，麻烦了

**Comment by CharlesJames13586** [comment]
```python
        # 加载本地字体文件,设置字体大小
        font_id = QFontDatabase.addApplicationFont(font_path)
        if font_id == -1:
            print("Failed to load font")
            return
        font_family = QFontDatabase.applicationFontFamilies(font_id)[0]
```
加了检测代码，提前退出相关函数可以正常运行了。
用大模型搞定了，我自己还没有细看代码
